### PR TITLE
Migrate license to Apache 2.0

### PR DESCRIPTION
**Pull request by ayyaruq**
As per request, even tho I don't personally care to be in the NOTICE file.

Permission granted by Nono, Levi, and Dis.

### CODE REVIEW

**Comment by ArcaneDisgea** [comment]
Just getting my permission in stone here! I agreed.

**Review by ArcaneDisgea — APPROVED** [review]

**Comment by SaltedLevity** [comment]
Also agree.

**Comment by ayyaruq** [comment]
Once merged, please issue a new release to update the license and notice on npm and the cdn.

**Comment by ghost** [comment]
I just got home. Let me review this tomorrow and make sure I understand the full ramifications of a license change. Since the other license holders have already said something in agreement here, I hope nobody would be offended that (if I approve) I hit the merge button.

Also, @ayyaruq - thanks for looking at the build system, and I'll push another release after I review.

**Pull request merged**
